apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: experiment
  namespace: ${NS}
spec:
  schedule: "@every 60s"
  concurrencyPolicy: Forbid
  historyLimit: 10
  type: NetworkChaos
  networkChaos:
    action: loss
    mode: one
    duration: 20s
    direction: both
    loss:
      loss: "10"
    selector:
      namespaces:
        - ${NS}
      labelSelectors:
        app.kubernetes.io/name: restate
    target:
      mode: all
      selector:
        namespaces:
          - ${NS}
        labelSelectors:
          app.kubernetes.io/name: restate
