name: Verification Compatibility Random

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *" # 00:12am UTC daily

jobs:
  verification-compatibility-random:
    name: Verification Compatibility Random
    strategy:
      fail-fast: false
      matrix:
        # Each released image below is run as a compatibility base against restate:main.
        releasedImage:
          - restatedev/restate:1.6.2
          - restatedev/restate:1.7.0
    uses: ./.github/workflows/verification-compatibility.yaml
    secrets: inherit
    with:
      mode: random
      releasedImage: ${{ matrix.releasedImage }}
