name: Verification Compatibility Backward

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *" # 00:12am UTC daily

jobs:
  verification-compatibility-backward:
    name: Verification Compatibility Backward
    uses: ./.github/workflows/verification-compatibility.yml
    secrets: inherit
    with:
      mode: backward
