name: Verification Performance tests

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *" # 00:12am UTC daily

jobs:
  verification-perf:
    name: Verification Performance tests
    uses: ./.github/workflows/verification-java.yaml
    secrets: inherit
    with:
      scenario: perf
