name: Verification tests with vqueues - Node

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *" # 00:12am UTC daily

jobs:
  verification-node-vqueues:
    name: Verification tests with vqueues - Node
    uses: ./.github/workflows/verification-node.yaml
    secrets: inherit
    with:
      scenario: vqueues
